

FROM python

RUN useradd -ms /bin/sh admin
COPY --chown=admin:admin . /lohrasb
 
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1
ENV username = $username
ENV password = $password
ENV gitusername = $gitusername
ENV gitpassword = $gitpassword
ENV POETRY_VERSION=1.2.2


RUN apt-get update
RUN apt-get install -y --no-install-recommends         gnumeric 
RUN apt-get install -y --no-install-recommends python3-pip


WORKDIR /lohrasb/lohrasb/data
RUN curl -O -k 'https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls' 
RUN  ssconvert default%20of%20credit%20card%20clients.xls data1.csv 
RUN  grep -v "X1" data1.csv > data.csv

# Install and setup poetry
WORKDIR /lohrasb
RUN pip install "poetry==$POETRY_VERSION"
RUN poetry config virtualenvs.create false 
RUN poetry install  --no-interaction --no-ansi

USER admin
RUN chmod +x ./run.sh

CMD ["bash", "./run.sh"]

