name: Python package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Upgrade pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # Install Nox
    - name: Install Nox
      run: pip install nox

    # Install Requirements
    - name: Install Requirements
      run: nox -s install_requirements
    # Run individual test sessions
    - name: Run test_optimize_by_tune
      run: nox -s test_optimize_by_tune

    - name: Run test_optimize_by_tunegridsearchcv
      run: nox -s test_optimize_by_tunegridsearchcv

    - name: Run test_optimize_by_optunasearch
      run: nox -s test_optimize_by_optunasearch

    - name: Run test_optimize_by_optunasearchcv
      run: nox -s test_optimize_by_optunasearchcv

    - name: Run test_optimize_by_tunerandomsearchcv
      run: nox -s test_optimize_by_tunerandomsearchcv

    - name: Run test_optimize_by_gridsearchcv
      run: nox -s test_optimize_by_gridsearchcv

    - name: Run test_optimize_by_randomsearchcv
      run: nox -s test_optimize_by_randomsearchcv

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up Python 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install twine for package upload
    - name: Install twine
      run: pip install twine

    # Build and publish to PyPI
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
